# Generated by Django 4.0.1 on 2022-01-12 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('member_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('email', models.CharField(default='', max_length=255)),
                ('joined', models.IntegerField(default=0)),
                ('last_visit', models.IntegerField(default=0)),
                ('last_activity', models.IntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('temp_ban', models.IntegerField(default=0)),
                ('pp_main_photo', models.TextField(null=True)),
                ('timezone', models.CharField(max_length=64, null=True)),
            ],
            options={
                'db_table': 'core_members',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('banned', models.BooleanField(default=False)),
                ('member_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MemberToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('ipb_token', models.CharField(max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
